// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Player documents
 */
interface PlayerDocumentData {
  /**
   * Image field in *Player*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: player.img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * Nome field in *Player*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: player.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;
}

/**
 * Player document from Prismic
 *
 * - **API ID**: `player`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlayerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PlayerDocumentData>, "player", Lang>;

/**
 * Item in *Sessao → Players*
 */
export interface SessaoDocumentDataPlayersItem {
  /**
   * Player field in *Sessao → Players*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: sessao.players[].player
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  player: prismic.ContentRelationshipField;
}

type SessaoDocumentDataSlicesSlice = never;

/**
 * Content for Sessao documents
 */
interface SessaoDocumentData {
  /**
   * Mapa field in *Sessao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sessao.mapa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mapa: prismic.KeyTextField;

  /**
   * Players field in *Sessao*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sessao.players[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  players: prismic.GroupField<Simplify<SessaoDocumentDataPlayersItem>>;

  /**
   * Slice Zone field in *Sessao*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sessao.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SessaoDocumentDataSlicesSlice> /**
   * Meta Description field in *Sessao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sessao.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sessao*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sessao.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Sessao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sessao.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Sessao document from Prismic
 *
 * - **API ID**: `sessao`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SessaoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SessaoDocumentData>, "sessao", Lang>;

export type AllDocumentTypes = PlayerDocument | SessaoDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PlayerDocument,
      PlayerDocumentData,
      SessaoDocument,
      SessaoDocumentData,
      SessaoDocumentDataPlayersItem,
      SessaoDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
